name: LBWBPlots
main: MyPlot\MyPlot
version: 1.0.0 MergeFixed
api: [3.0.0, 3.17.5, 4.0.0]
authors:
- LBWB
- Zer0YT
- McLebt
softdepend:
- PocketMoney
- EssentialsPE
- DEVirion
- WorldStyler
- EconomyAPI
extensions:
- sqlite3
- yaml
permissions:
  myplot.command:
    default: op
    children:
      normal:
        default: true
      myplot.command.help:
        default: true
      myplot.command.claim:
        default: true
      myplot.command.info:
        default: true
      myplot.command.generate:
        default: op
      myplot.command.reload:
        default: op
      myplot.command.trust:
        default: true
      myplot.command.untrust:
        default: true
      myplot.command.ban:
        default: true
      myplot.command.unban:
        default: true
      myplot.command.auto:
        default: true
      myplot.command.clear:
        default: true
      myplot.command.dispose:
        default: true
      myplot.command.reset:
        default: true
      myplot.command.home:
        default: true
      myplot.command.homes:
        default: true
      myplot.command.name:
        default: true
      myplot.command.give:
        default: true
      myplot.command.warp:
        default: true
      myplot.command.done:
        default: true
      myplot.command.merge:
        default: op
      myplot.command.fill:
        default: true
      myplot.command.unmerge:
        default: op
      myplot.command.middle:
        default: true
      myplot.command.list:
        default: true
      myplot.command.unfill:
        default: true
      myplot.command.kick:
        default: true
      myplot.command.rand:
        default: true
      myplot.command.wand:
        default: true
  myplot.admin:
    default: op
    children:
      myplot.admin.clear:
        default: op
      myplot.admin.dispose:
        default: op
      myplot.admin.reset:
        default: op
      myplot.admin.addhelper:
        default: op
      myplot.admin.removehelper:
        default: op
      myplot.admin.denyplayer:
        default: op
        children:
          myplot.admin.denyplayer.bypass:
            default: op
      myplot.admin.undenyplayer:
        default: op
      myplot.admin.build:
        default: op
        children:
          myplot.admin.build.plot:
            default: op
          myplot.admin.build.road:
            default: op
      myplot.admin.name:
        default: op
      myplot.admin.warp:
        default: op
      myplot.admin.done:
        default: op
      myplot.admin.merge:
        default: op
      myplot.admin.fill:
        default: op
      myplot.admin.unmerge:
        default: op
      myplot.admin.middle:
        default: true
      myplot.admin.list:
        default: op
  myplot.claimplots:
    default: op
    children:
      myplot.claimplots.3:
        default: true
      myplot.claimplots.unlimited:
        default: op
